// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

package com.snapchat.client.valdi_core;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Owns a set of native object references tied to a scope. When destroyed via
 * destroyNativeObjectsManager, all native references in this scope are released
 * immediately rather than waiting for JS garbage collection.
 *
 * Typically each bounded task creates its own manager and destroys it when done.
 * See the platform-specific APIs (IValdiRuntime on Android, SCValdiJSRuntime
 * on iOS) for guidance on recommended usage patterns.
 */
public abstract class JSRuntimeNativeObjectsManager {
    public abstract java.lang.Object getReachableObjectsDescription();

    public static final class CppProxy extends JSRuntimeNativeObjectsManager
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public java.lang.Object getReachableObjectsDescription()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getReachableObjectsDescription(this.nativeRef);
        }
        private native java.lang.Object native_getReachableObjectsDescription(long _nativeRef);
    }
}
