// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#import <Foundation/Foundation.h>
@class SCNValdiCoreJSRuntime;
@class SCNValdiCoreJSRuntimeNativeObjectsManager;


@interface SCNValdiCoreJSRuntime : NSObject

/**
 * Push the module unmarshalled using the schema in the given marshaller handle
 * into the marshaller.
 */
- (int32_t)pushModuleToMarshaller:(nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)nativeObjectsManager
                             path:(nonnull NSString *)path
                 marshallerHandle:(int64_t)marshallerHandle;

- (void)addModuleUnloadObserver:(nonnull NSString *)path
                       observer:(nonnull NSObject *)observer;

- (void)preloadModule:(nonnull NSString *)path
             maxDepth:(int32_t)maxDepth;

- (nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)createNativeObjectsManagerWithScopeName:(nonnull NSString *)scopeName;

- (void)destroyNativeObjectsManager:(nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)nativeObjectsManager;

- (nullable SCNValdiCoreJSRuntime *)createWorker;

- (void)runOnJsThread:(nonnull NSObject *)runnable;

@end
