// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from valdi_core.djinni

#ifdef __cplusplus
#import "valdi_core/SCNValdiCoreJSRuntime+Private.h"
#import "valdi_core/SCNValdiCoreJSRuntime.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "valdi_core/SCNValdiCoreJSRuntimeNativeObjectsManager+Private.h"
#import "valdi_core/bindings/InternedStringTranslator_objc.hpp"
#import "valdi_core/bindings/ValueTranslator_objc.hpp"
#include "utils/debugging/DjinniPrologue.hpp"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SCNValdiCoreJSRuntime ()

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::JSRuntime>&)cppRef;

@end

@implementation SCNValdiCoreJSRuntime {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::snap::valdi_core::JSRuntime>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::snap::valdi_core::JSRuntime>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (int32_t)pushModuleToMarshaller:(nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)nativeObjectsManager
                             path:(nonnull NSString *)path
                 marshallerHandle:(int64_t)marshallerHandle {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.pushModuleToMarshaller");
        auto objcpp_result_ = _cppRefHandle.get()->pushModuleToMarshaller(::djinni_generated_client::valdi_core::JSRuntimeNativeObjectsManager::toCpp(nativeObjectsManager),
                                                                          ValdiIOS::InternedStringTranslator::toCpp(path),
                                                                          ::djinni::I64::toCpp(marshallerHandle));
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)addModuleUnloadObserver:(nonnull NSString *)path
                       observer:(nonnull NSObject *)observer {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.addModuleUnloadObserver");
        _cppRefHandle.get()->addModuleUnloadObserver(ValdiIOS::InternedStringTranslator::toCpp(path),
                                                     ValdiIOS::ValueTranslator::toCpp(observer));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)preloadModule:(nonnull NSString *)path
             maxDepth:(int32_t)maxDepth {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.preloadModule");
        _cppRefHandle.get()->preloadModule(ValdiIOS::InternedStringTranslator::toCpp(path),
                                           ::djinni::I32::toCpp(maxDepth));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)createNativeObjectsManagerWithScopeName:(nonnull NSString *)scopeName {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.createNativeObjectsManager");
        auto objcpp_result_ = _cppRefHandle.get()->createNativeObjectsManager(::djinni::String::toCpp(scopeName));
        return ::djinni_generated_client::valdi_core::JSRuntimeNativeObjectsManager::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)destroyNativeObjectsManager:(nullable SCNValdiCoreJSRuntimeNativeObjectsManager *)nativeObjectsManager {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.destroyNativeObjectsManager");
        _cppRefHandle.get()->destroyNativeObjectsManager(::djinni_generated_client::valdi_core::JSRuntimeNativeObjectsManager::toCpp(nativeObjectsManager));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable SCNValdiCoreJSRuntime *)createWorker {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.createWorker");
        auto objcpp_result_ = _cppRefHandle.get()->createWorker();
        return ::djinni_generated_client::valdi_core::JSRuntime::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)runOnJsThread:(nonnull NSObject *)runnable {
    try {
        DJINNI_FUNCTION_PROLOGUE("JSRuntime.runOnJsThread");
        _cppRefHandle.get()->runOnJsThread(ValdiIOS::ValueTranslator::toCpp(runnable));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated_client::valdi_core {

auto JSRuntime::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto JSRuntime::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SCNValdiCoreJSRuntime>(cpp);
}

} // namespace djinni_generated_client::valdi_core

@end
#endif // __cplusplus
